// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB673sr6lko8AVI9VlpaH8wgpix--Wen2Q',
    appId: '1:680400422008:android:f94680ebeaf74d7cdd998d',
    messagingSenderId: '680400422008',
    projectId: 'my-english-app-eccc8',
    storageBucket: 'my-english-app-eccc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxFWfKwiz91CCUsWdmpdbgMeWLp0OpCy4',
    appId: '1:680400422008:ios:0f808f9071985448dd998d',
    messagingSenderId: '680400422008',
    projectId: 'my-english-app-eccc8',
    storageBucket: 'my-english-app-eccc8.firebasestorage.app',
    iosBundleId: 'com.example.myEnglishApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCefsf7eGnvAHQiV028J_gtsh3d_7Izo6o',
    appId: '1:680400422008:web:64f657149de5e373dd998d',
    messagingSenderId: '680400422008',
    projectId: 'my-english-app-eccc8',
    authDomain: 'my-english-app-eccc8.firebaseapp.com',
    storageBucket: 'my-english-app-eccc8.firebasestorage.app',
  );
}
